package entity;

public class BoardTemplate {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_s_board.Level
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    private Integer level;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_s_board.Board
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    private String board;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_s_board.Level
     * @return  the value of t_s_board.Level
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_s_board.Level
     * @param level  the value for t_s_board.Level
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_s_board.Board
     * @return  the value of t_s_board.Board
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public String getBoard() {
        return board;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_s_board.Board
     * @param board  the value for t_s_board.Board
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public void setBoard(String board) {
        this.board = board;
    }
}