package entity;

import java.util.Date;

public class LockInfo {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_u_lock.SessionId
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    private String sessionid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_u_lock.UpdateTime
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_u_lock.SessionId
     * @return  the value of t_u_lock.SessionId
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_u_lock.SessionId
     * @param sessionid  the value for t_u_lock.SessionId
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_u_lock.UpdateTime
     * @return  the value of t_u_lock.UpdateTime
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_u_lock.UpdateTime
     * @param updatetime  the value for t_u_lock.UpdateTime
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}