package mapper;

import entity.LockInfo;
import entity.LockInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LockInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    long countByExample(LockInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int deleteByExample(LockInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int deleteByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int insert(LockInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int insertSelective(LockInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    List<LockInfo> selectByExample(LockInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    LockInfo selectByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") LockInfo record, @Param("example") LockInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByExample(@Param("record") LockInfo record, @Param("example") LockInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(LockInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_lock
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByPrimaryKey(LockInfo record);
}