package mapper;

import entity.PlayerInfo;
import entity.PlayerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    long countByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int deleteByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int deleteByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int insert(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int insertSelective(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    List<PlayerInfo> selectByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    PlayerInfo selectByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") PlayerInfo record, @Param("example") PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByExample(@Param("record") PlayerInfo record, @Param("example") PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_u_player
     * @mbg.generated  Sun May 19 17:39:03 CST 2019
     */
    int updateByPrimaryKey(PlayerInfo record);
}